package persistencia.dao;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import Logica.Operario;
import Logica.OrdenVenta;
import persistencia.DatabaseConnection;

public class OrdenVentaDAO {

    public void addOrdenVenta(OrdenVenta orden) {
        String sql = "INSERT INTO orden_venta (numero_orden, id_trabajador, id_prenda, cliente, tipo_venta, precio_final, cantidad_vendida) VALUES (?, ?, ?, ?, ?, ?, ?)";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            pstmt.setInt(1, orden.getNumeroOrden());
            pstmt.setFloat(2, ((Operario) orden.getOperarioVentas()).getId());
            pstmt.setInt(3, ((Object) orden.getPrendaVendida()).getIdPrenda());
            pstmt.setString(4, orden.getCliente());
            pstmt.setString(5, orden.getTipoVenta());
            pstmt.setDouble(6, orden.getPrecioFinal());
            pstmt.setInt(7, orden.getCantidadVendida());
            pstmt.executeUpdate();

            // No need to get generated keys for numero_orden if it's generated by app,
            // but if id_orden is needed, you'd retrieve it here.
            System.out.println("Orden de venta #" + orden.getNumeroOrden() + " registrada con éxito.");

        } catch (SQLException e) {
            System.err.println("Error al registrar orden de venta: " + e.getMessage());
        }
    }

    public List<OrdenVenta> getAllOrdenesVenta() {
        List<OrdenVenta> ordenes = new ArrayList<>();
        String sql = "SELECT ov.numero_orden, ov.cliente, ov.tipo_venta, ov.precio_final, ov.cantidad_vendida, " +
                     "u.id AS operario_id, u.usuario AS operario_nombre, " +
                     "p.id_prenda, p.tipo_prenda, p.genero, p.temporada, p.estilo, p.costo_base_por_unidad, ipr.cantidad_disponible " +
                     "FROM orden_venta ov " +
                     "JOIN usuario u ON ov.id_trabajador = u.id " +
                     "JOIN prenda p ON ov.id_prenda = p.id_prenda " +
                     "LEFT JOIN inventario_producto_refinado ipr ON p.id_prenda = ipr.id_prenda";

        try (Connection conn = DatabaseConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                int numeroOrden = rs.getInt("numero_orden");
                String cliente = rs.getString("cliente");
                String tipoVenta = rs.getString("tipo_venta");
                double precioFinal = rs.getDouble("precio_final");
                int cantidadVendida = rs.getInt("cantidad_vendida");

                // Operario
                int operarioId = rs.getInt("operario_id");
                String operarioNombre = rs.getString("operario_nombre");
                Operario operario = new Operario(operarioId, operarioNombre);

                // Prenda
                int idPrenda = rs.getInt("id_prenda");
                String tipoPrenda = rs.getString("tipo_prenda");
                String genero = rs.getString("genero");
                String temporada = rs.getString("temporada");
                String estilo = rs.getString("estilo");
                double costoBase = rs.getDouble("costo_base_por_unidad");
                int cantidadDisponible = rs.getInt("cantidad_disponible"); // This is from inventory, not necessarily what was sold
                Prenda prenda = new Prenda(idPrenda, tipoPrenda, genero, temporada, estilo, costoBase, cantidadDisponible);

                ordenes.add(new OrdenVenta(numeroOrden, operario, prenda, cliente, tipoVenta, precioFinal, cantidadVendida));
            }
        } catch (SQLException e) {
            System.err.println("Error al obtener órdenes de venta: " + e.getMessage());
        }
        return ordenes;
    }
}